language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
 provider: heroku
 api_key:
   secure: GafQntqZKSyGVagQ26adCqDFHBpOZ79cNlqt2MYJalnaXthQm0g71QuYdSQJCBW6Wz1FmvVmWP2CdQ29+hiyWuDvhodmEOFNcGsRIpl+4yHVELLKLXUYDZqGFtr6MIXyvAvTxhOK9p+C/rtnjDpozZzqPFoXxquAzsnlgySDy1bkvs/BdGKS8J8wbh8j8nCJmFJFkJ4YSknRaNP4cyZS0QOhKWSYtn+Mzgfmiz0O0BJ3Owa1pwmkpIRKY7vpKUYEb9KAKM8o153cGI40UjcDAduINbW61krJ8VFN6EumcivlApsdKE5VoXqTgprUTs9fayBWagQPOHoFkj0Z4W5QaQWxV2iCaZeRNd4m+3eT+aCijbiNeyP+BjEYhuTJik/4zmLHHBZEKwMw9k0m4IZY01PpeBiY4esTh+BjWvATswusTOTLs30bS4slgWAWfqgU7N8+S3vT2aUzR+IouujscgmVXypnNwePt0o86kog9EZRyGT0XwX3Ow5H70NtYF1seJRz4JqYJWHv3xH8bHvdGBfVtOqBCmlh9bSYxTdBIsFvq6Bdt5bnQKCdkP1JHYkt28Ko+NpKh1j/MTh9scmPPt5R7Dzd6mo4xJscOElYhGRVg3y6kbi1lVEEtN3oUmHxBSDK2iPEJrrcT6TVZREyB+nUDwjq3DULorPcLmVywKY=
 app: skeleton-in-the-closet
